# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowSettings.ui'
#
# Created: Thu Oct 10 10:46:46 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_windowSettings(object):
    def setupUi(self, windowSettings):
        windowSettings.setObjectName(_fromUtf8("windowSettings"))
        windowSettings.resize(770, 230)
        self.centralwidget = QtGui.QWidget(windowSettings)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabNES = QtGui.QWidget()
        self.tabNES.setObjectName(_fromUtf8("tabNES"))
        self.gridLayout = QtGui.QGridLayout(self.tabNES)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.tabNES)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tabNES)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.pathNES = QtGui.QLineEdit(self.tabNES)
        self.pathNES.setObjectName(_fromUtf8("pathNES"))
        self.gridLayout.addWidget(self.pathNES, 1, 1, 1, 1)
        self.openBinNES = QtGui.QPushButton(self.tabNES)
        self.openBinNES.setObjectName(_fromUtf8("openBinNES"))
        self.gridLayout.addWidget(self.openBinNES, 1, 2, 1, 1)
        self.cmdNES = QtGui.QLineEdit(self.tabNES)
        self.cmdNES.setObjectName(_fromUtf8("cmdNES"))
        self.gridLayout.addWidget(self.cmdNES, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tabNES, _fromUtf8(""))
        self.tabSNES = QtGui.QWidget()
        self.tabSNES.setObjectName(_fromUtf8("tabSNES"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabSNES)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.tabSNES)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.pathSNES = QtGui.QLineEdit(self.tabSNES)
        self.pathSNES.setObjectName(_fromUtf8("pathSNES"))
        self.gridLayout_2.addWidget(self.pathSNES, 0, 1, 1, 1)
        self.openBinSNES = QtGui.QPushButton(self.tabSNES)
        self.openBinSNES.setObjectName(_fromUtf8("openBinSNES"))
        self.gridLayout_2.addWidget(self.openBinSNES, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.tabSNES)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.cmdSNES = QtGui.QLineEdit(self.tabSNES)
        self.cmdSNES.setObjectName(_fromUtf8("cmdSNES"))
        self.gridLayout_2.addWidget(self.cmdSNES, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabSNES, _fromUtf8(""))
        self.tabN64 = QtGui.QWidget()
        self.tabN64.setObjectName(_fromUtf8("tabN64"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabN64)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_8 = QtGui.QLabel(self.tabN64)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.pathN64 = QtGui.QLineEdit(self.tabN64)
        self.pathN64.setObjectName(_fromUtf8("pathN64"))
        self.gridLayout_4.addWidget(self.pathN64, 0, 1, 1, 1)
        self.openBinN64 = QtGui.QPushButton(self.tabN64)
        self.openBinN64.setObjectName(_fromUtf8("openBinN64"))
        self.gridLayout_4.addWidget(self.openBinN64, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.tabN64)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.cmdN64 = QtGui.QLineEdit(self.tabN64)
        self.cmdN64.setObjectName(_fromUtf8("cmdN64"))
        self.gridLayout_4.addWidget(self.cmdN64, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabN64, _fromUtf8(""))
        self.tabGC = QtGui.QWidget()
        self.tabGC.setObjectName(_fromUtf8("tabGC"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabGC)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_10 = QtGui.QLabel(self.tabGC)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.pathGameCube = QtGui.QLineEdit(self.tabGC)
        self.pathGameCube.setObjectName(_fromUtf8("pathGameCube"))
        self.gridLayout_5.addWidget(self.pathGameCube, 0, 1, 1, 1)
        self.openBinGameCube = QtGui.QPushButton(self.tabGC)
        self.openBinGameCube.setObjectName(_fromUtf8("openBinGameCube"))
        self.gridLayout_5.addWidget(self.openBinGameCube, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.tabGC)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 1)
        self.cmdGameCube = QtGui.QLineEdit(self.tabGC)
        self.cmdGameCube.setObjectName(_fromUtf8("cmdGameCube"))
        self.gridLayout_5.addWidget(self.cmdGameCube, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabGC, _fromUtf8(""))
        self.tabWii = QtGui.QWidget()
        self.tabWii.setObjectName(_fromUtf8("tabWii"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabWii)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_12 = QtGui.QLabel(self.tabWii)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 0, 0, 1, 1)
        self.pathWii = QtGui.QLineEdit(self.tabWii)
        self.pathWii.setObjectName(_fromUtf8("pathWii"))
        self.gridLayout_6.addWidget(self.pathWii, 0, 1, 1, 1)
        self.openBinWii = QtGui.QPushButton(self.tabWii)
        self.openBinWii.setObjectName(_fromUtf8("openBinWii"))
        self.gridLayout_6.addWidget(self.openBinWii, 0, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.tabWii)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 1, 0, 1, 1)
        self.cmdWii = QtGui.QLineEdit(self.tabWii)
        self.cmdWii.setObjectName(_fromUtf8("cmdWii"))
        self.gridLayout_6.addWidget(self.cmdWii, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabWii, _fromUtf8(""))
        self.tabPS1 = QtGui.QWidget()
        self.tabPS1.setObjectName(_fromUtf8("tabPS1"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabPS1)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_14 = QtGui.QLabel(self.tabPS1)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_7.addWidget(self.label_14, 0, 0, 1, 1)
        self.pathPS1 = QtGui.QLineEdit(self.tabPS1)
        self.pathPS1.setObjectName(_fromUtf8("pathPS1"))
        self.gridLayout_7.addWidget(self.pathPS1, 0, 1, 1, 1)
        self.openBinPS1 = QtGui.QPushButton(self.tabPS1)
        self.openBinPS1.setObjectName(_fromUtf8("openBinPS1"))
        self.gridLayout_7.addWidget(self.openBinPS1, 0, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.tabPS1)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_7.addWidget(self.label_15, 1, 0, 1, 1)
        self.cmdPS1 = QtGui.QLineEdit(self.tabPS1)
        self.cmdPS1.setObjectName(_fromUtf8("cmdPS1"))
        self.gridLayout_7.addWidget(self.cmdPS1, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabPS1, _fromUtf8(""))
        self.tabPS2 = QtGui.QWidget()
        self.tabPS2.setObjectName(_fromUtf8("tabPS2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabPS2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_16 = QtGui.QLabel(self.tabPS2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_8.addWidget(self.label_16, 0, 0, 1, 1)
        self.pathPS2 = QtGui.QLineEdit(self.tabPS2)
        self.pathPS2.setObjectName(_fromUtf8("pathPS2"))
        self.gridLayout_8.addWidget(self.pathPS2, 0, 1, 1, 1)
        self.openBinPS2 = QtGui.QPushButton(self.tabPS2)
        self.openBinPS2.setObjectName(_fromUtf8("openBinPS2"))
        self.gridLayout_8.addWidget(self.openBinPS2, 0, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.tabPS2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_8.addWidget(self.label_17, 1, 0, 1, 1)
        self.cmdPS2 = QtGui.QLineEdit(self.tabPS2)
        self.cmdPS2.setObjectName(_fromUtf8("cmdPS2"))
        self.gridLayout_8.addWidget(self.cmdPS2, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabPS2, _fromUtf8(""))
        self.tabGenesis = QtGui.QWidget()
        self.tabGenesis.setObjectName(_fromUtf8("tabGenesis"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tabGenesis)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_18 = QtGui.QLabel(self.tabGenesis)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_9.addWidget(self.label_18, 0, 0, 1, 1)
        self.pathGenesis = QtGui.QLineEdit(self.tabGenesis)
        self.pathGenesis.setObjectName(_fromUtf8("pathGenesis"))
        self.gridLayout_9.addWidget(self.pathGenesis, 0, 1, 1, 1)
        self.openBinGenesis = QtGui.QPushButton(self.tabGenesis)
        self.openBinGenesis.setObjectName(_fromUtf8("openBinGenesis"))
        self.gridLayout_9.addWidget(self.openBinGenesis, 0, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.tabGenesis)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_9.addWidget(self.label_19, 1, 0, 1, 1)
        self.cmdGenesis = QtGui.QLineEdit(self.tabGenesis)
        self.cmdGenesis.setObjectName(_fromUtf8("cmdGenesis"))
        self.gridLayout_9.addWidget(self.cmdGenesis, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabGenesis, _fromUtf8(""))
        self.tabDreamcast = QtGui.QWidget()
        self.tabDreamcast.setObjectName(_fromUtf8("tabDreamcast"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tabDreamcast)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_20 = QtGui.QLabel(self.tabDreamcast)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_10.addWidget(self.label_20, 0, 0, 1, 1)
        self.pathDreamcast = QtGui.QLineEdit(self.tabDreamcast)
        self.pathDreamcast.setObjectName(_fromUtf8("pathDreamcast"))
        self.gridLayout_10.addWidget(self.pathDreamcast, 0, 1, 1, 1)
        self.openBinDreamcast = QtGui.QPushButton(self.tabDreamcast)
        self.openBinDreamcast.setObjectName(_fromUtf8("openBinDreamcast"))
        self.gridLayout_10.addWidget(self.openBinDreamcast, 0, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.tabDreamcast)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_10.addWidget(self.label_21, 1, 0, 1, 1)
        self.cmdDreamcast = QtGui.QLineEdit(self.tabDreamcast)
        self.cmdDreamcast.setObjectName(_fromUtf8("cmdDreamcast"))
        self.gridLayout_10.addWidget(self.cmdDreamcast, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabDreamcast, _fromUtf8(""))
        self.tabGameBoy = QtGui.QWidget()
        self.tabGameBoy.setObjectName(_fromUtf8("tabGameBoy"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tabGameBoy)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_22 = QtGui.QLabel(self.tabGameBoy)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_11.addWidget(self.label_22, 0, 0, 1, 1)
        self.pathGameBoy = QtGui.QLineEdit(self.tabGameBoy)
        self.pathGameBoy.setObjectName(_fromUtf8("pathGameBoy"))
        self.gridLayout_11.addWidget(self.pathGameBoy, 0, 1, 1, 1)
        self.openBinGameBoy = QtGui.QPushButton(self.tabGameBoy)
        self.openBinGameBoy.setObjectName(_fromUtf8("openBinGameBoy"))
        self.gridLayout_11.addWidget(self.openBinGameBoy, 0, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.tabGameBoy)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_11.addWidget(self.label_23, 1, 0, 1, 1)
        self.cmdGameBoy = QtGui.QLineEdit(self.tabGameBoy)
        self.cmdGameBoy.setObjectName(_fromUtf8("cmdGameBoy"))
        self.gridLayout_11.addWidget(self.cmdGameBoy, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabGameBoy, _fromUtf8(""))
        self.tabGBA = QtGui.QWidget()
        self.tabGBA.setObjectName(_fromUtf8("tabGBA"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tabGBA)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_24 = QtGui.QLabel(self.tabGBA)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_12.addWidget(self.label_24, 0, 0, 1, 1)
        self.pathGBA = QtGui.QLineEdit(self.tabGBA)
        self.pathGBA.setObjectName(_fromUtf8("pathGBA"))
        self.gridLayout_12.addWidget(self.pathGBA, 0, 1, 1, 1)
        self.openBinGBA = QtGui.QPushButton(self.tabGBA)
        self.openBinGBA.setObjectName(_fromUtf8("openBinGBA"))
        self.gridLayout_12.addWidget(self.openBinGBA, 0, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.tabGBA)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_12.addWidget(self.label_25, 1, 0, 1, 1)
        self.cmdGBA = QtGui.QLineEdit(self.tabGBA)
        self.cmdGBA.setObjectName(_fromUtf8("cmdGBA"))
        self.gridLayout_12.addWidget(self.cmdGBA, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabGBA, _fromUtf8(""))
        self.tabNDS = QtGui.QWidget()
        self.tabNDS.setObjectName(_fromUtf8("tabNDS"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tabNDS)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_26 = QtGui.QLabel(self.tabNDS)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_13.addWidget(self.label_26, 0, 0, 1, 1)
        self.pathNDS = QtGui.QLineEdit(self.tabNDS)
        self.pathNDS.setObjectName(_fromUtf8("pathNDS"))
        self.gridLayout_13.addWidget(self.pathNDS, 0, 1, 1, 1)
        self.openBinNDS = QtGui.QPushButton(self.tabNDS)
        self.openBinNDS.setObjectName(_fromUtf8("openBinNDS"))
        self.gridLayout_13.addWidget(self.openBinNDS, 0, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.tabNDS)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_13.addWidget(self.label_27, 1, 0, 1, 1)
        self.cmdNDS = QtGui.QLineEdit(self.tabNDS)
        self.cmdNDS.setObjectName(_fromUtf8("cmdNDS"))
        self.gridLayout_13.addWidget(self.cmdNDS, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabNDS, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnSave = QtGui.QPushButton(self.centralwidget)
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnCancel = QtGui.QPushButton(self.centralwidget)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout.addWidget(self.btnCancel)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        windowSettings.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(windowSettings)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 770, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        windowSettings.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(windowSettings)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        windowSettings.setStatusBar(self.statusbar)

        self.retranslateUi(windowSettings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(windowSettings)

    def retranslateUi(self, windowSettings):
        windowSettings.setWindowTitle(_translate("windowSettings", "Ice - Settings", None))
        self.label_4.setText(_translate("windowSettings", "Path to emulator binary:", None))
        self.label_5.setText(_translate("windowSettings", "Custom commands:", None))
        self.openBinNES.setText(_translate("windowSettings", "Open binary...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNES), _translate("windowSettings", "NES", None))
        self.label_6.setText(_translate("windowSettings", "Path to emulator binary:", None))
        self.openBinSNES.setText(_translate("windowSettings", "Open binary...", None))
        self.label_7.setText(_translate("windowSettings", "Custom commands:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSNES), _translate("windowSettings", "SNES", None))
        self.label_8.setText(_translate("windowSettings", "Path to emulator binary:", None))
        self.openBinN64.setText(_translate("windowSettings", "Open binary...", None))
        self.label_9.setText(_translate("windowSettings", "Custom commands:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabN64), _translate("windowSettings", "N64", None))
        self.label_10.setText(_translate("windowSettings", "Path to emulator binary:", None))
        self.openBinGameCube.setText(_translate("windowSettings", "Open binary...", None))
        self.label_11.setText(_translate("windowSettings", "Custom commands:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGC), _translate("windowSettings", "GameCube", None))
        self.label_12.setText(_translate("windowSettings", "Path to emulator binary:", None))
        self.openBinWii.setText(_translate("windowSettings", "Open binary...", None))
        self.label_13.setText(_translate("windowSettings", "Custom commands:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWii), _translate("windowSettings", "Wii", None))
        self.label_14.setText(_translate("windowSettings", "Path to emulator binary:", None))
        self.openBinPS1.setText(_translate("windowSettings", "Open binary...", None))
        self.label_15.setText(_translate("windowSettings", "Custom commands:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPS1), _translate("windowSettings", "PS 1", None))
        self.label_16.setText(_translate("windowSettings", "Path to emulator binary:", None))
        self.openBinPS2.setText(_translate("windowSettings", "Open binary...", None))
        self.label_17.setText(_translate("windowSettings", "Custom commands:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPS2), _translate("windowSettings", "PS 2", None))
        self.label_18.setText(_translate("windowSettings", "Path to emulator binary:", None))
        self.openBinGenesis.setText(_translate("windowSettings", "Open binary...", None))
        self.label_19.setText(_translate("windowSettings", "Custom commands:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGenesis), _translate("windowSettings", "Genesis", None))
        self.label_20.setText(_translate("windowSettings", "Path to emulator binary:", None))
        self.openBinDreamcast.setText(_translate("windowSettings", "Open binary...", None))
        self.label_21.setText(_translate("windowSettings", "Custom commands:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDreamcast), _translate("windowSettings", "Dreamcast", None))
        self.label_22.setText(_translate("windowSettings", "Path to emulator binary:", None))
        self.openBinGameBoy.setText(_translate("windowSettings", "Open binary...", None))
        self.label_23.setText(_translate("windowSettings", "Custom commands:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGameBoy), _translate("windowSettings", "GameBoy", None))
        self.label_24.setText(_translate("windowSettings", "Path to emulator binary:", None))
        self.openBinGBA.setText(_translate("windowSettings", "Open binary...", None))
        self.label_25.setText(_translate("windowSettings", "Custom commands:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGBA), _translate("windowSettings", "GBA", None))
        self.label_26.setText(_translate("windowSettings", "Path to emulator binary:", None))
        self.openBinNDS.setText(_translate("windowSettings", "Open binary...", None))
        self.label_27.setText(_translate("windowSettings", "Custom commands:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNDS), _translate("windowSettings", "NDS", None))
        self.btnSave.setText(_translate("windowSettings", "Save", None))
        self.btnCancel.setText(_translate("windowSettings", "Cancel", None))

